name: Notify Lark After Vercel Deployment

on:
  push:
    branches:
      - main
      - develop

jobs:
  notify-lark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send success notification to Lark
        run: |
          curl -X POST ${{ secrets.LARK_WEBHOOK_URL }} \
          -H 'Content-Type: application/json' \
          -d '{
            "msg_type": "text",
            "content": {
              "text": "Vercel 发布中... ${{ env.PROJECT_NAME }} 项目已成功发布，等待3-5分钟，部署后访问地址： ${{ secrets.VERCEL_DEPLOYMENT_URL }}"
            }
          }'
